version: "3.7"

x-redis-base: &redis-base
  image: docker.io/bitnami/redis-cluster:7.0.10
  networks:
    - redis-cluster-net
  environment:
    - REDIS_CLUSTER_DYNAMIC_IPS=no
    - ALLOW_EMPTY_PASSWORD=yes

networks:
  redis-cluster-net:
    driver: bridge

services:
  cache:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - redis-cluster-net

  redis-node-0:
    container_name: redis-node-0
    <<: *redis-base
    ports:
      - 6370:6379
      - 16370:16379
    environment:
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-0
      - REDIS_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-0:6379 redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379

  redis-node-1:
    container_name: redis-node-1
    <<: *redis-base
    ports:
      - 6371:6379
      - 16371:16379
    environment:
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-1
      - REDIS_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-0:6379 redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379

  redis-node-2:
    container_name: redis-node-2
    <<: *redis-base
    ports:
      - 6372:6379
      - 16372:16379
    environment:
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-2
      - REDIS_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-0:6379 redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379

  redis-node-3:
    container_name: redis-node-3
    <<: *redis-base
    ports:
      - 6373:6379
      - 16373:16379
    environment:
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-3
      - REDIS_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-0:6379 redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379

  redis-node-4:
    container_name: redis-node-4
    <<: *redis-base
    ports:
      - 6374:6379
      - 16374:16379
    environment:
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-4
      - REDIS_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-0:6379 redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379

  redis-node-5:
    container_name: redis-node-5
    <<: *redis-base
    ports:
      - 6375:6379
      - 16375:16379
    environment:
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-5
      - REDIS_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-0:6379 redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_CLUSTER_CREATOR=yes